	#include <stdio.h>
#include <stdlib.h>

/* 
Parte 1
PESQUISE UM USO REAL DE PILHA EM PROBLEMAS COM ALGORITMOS
APRESENTE O PROBLEMA
IMPLEMENTE O PROBLEMA EM C USANDO AMBAS AS FORMAS (OU IMPLEMENTE UM PROBLEMA PARA CADA FORMA):
-VETOR
-LISTA ENCADEADA (CRIAR UM TAD PILHA COM AS FUNÇÕES DEFINIDAS ANTERIORMENTE) 

Parte 2
PESQUISE UM USO REAL DE FILAS EM PROBLEMAS COM ALGORITMOS
APRESENTE O PROBLEMA
IMPLEMENTE O PROBLEMA EM C USANDO AMBAS AS FORMAS (OU IMPLEMENTE UM PROBLEMA PARA CADA FORMA):
-FILA CIRCULAR
-LISTA ENCADEADA (CRIAR UM TAD FILA COM AS FUNÇÕES DEFINIDAS ANTERIORMENTE) 
*/

int main(int argc, char *argv[]) {
	return 0;
}
